let comments = [
  {
    commentId: 0,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.',
  },
  {
    commentId: 1,
    email: 'bin000527@naver.com',
    storeId: '26571895',
    content: '짱짱!',
  },
  {
    commentId: 2,
    email: 'bin000527@naver.com',
    storeId: '27514796',
    content: '내 최애임',
  },
  {
    commentId: 3,
    email: 'rok.ksohn@gmail.com',
    storeId: '27514796',
    content: '여기 별로',
  },
  {
    commentId: 4,
    email: 'alswl99710@gmail.com',
    storeId: '589846825',
    content: '여기 단골인데 사장님 너무 좋아요 ㅎㅎㅎㅎㅎㅎ',
  },
  {
    commentId: 5,
    email: 'rok.ksohn@gmail.com',
    storeId: '589846825',
    content: '맨날 가는 맛집',
  },
  {
    commentId: 6,
    email: 'rok.ksohn@gmail.com',
    storeId: '20328809',
    content: '규성이가 자신 있게 추천하는 맛집! ',
  },
  {
    commentId: 7,
    email: 'alswl99710@gmail.com',
    storeId: '20328809',
    content: '여기 단골인데 사장님 너무 좋아요 ㅎㅎㅎㅎㅎㅎ',
  },
  {
    commentId: 8,
    email: 'rok.ksohn@gmail.com',
    storeId: '427510472',
    content: '콜라 너무 맛있어요',
  },
  {
    commentId: 9,
    email: 'sanbondeveloper@gmail.com',
    storeId: '427510472',
    content: '사이다가 더 맛있음',
  },
  {
    commentId: 10,
    email: 'alswl99710@gmail.com',
    storeId: '427510472',
    content: '짱',
  },
  {
    commentId: 11,
    email: 'sanbondeveloper@gmail.com',
    storeId: '682483214',
    content: '최애 맛집. 한 번 가면 못 빠져나온다.',
  },
  {
    commentId: 12,
    email: 'rok.ksohn@gmail.com',
    storeId: '682483214',
    content: '아버님도 너무 좋아하세요 ~',
  },
  {
    commentId: 13,
    email: 'bin000527@naver.com',
    storeId: '682483214',
    content: '술 마시면 꼭 2차로 들리는 곳',
  },
  {
    commentId: 14,
    email: 'sanbondeveloper@gmail.com',
    storeId: '19037502',
    content: '굿',
  },
  {
    commentId: 15,
    email: 'alswl99710@gmail.com',
    storeId: '19037502',
    content: '굿굿',
  },
  {
    commentId: 16,
    email: 'rok.ksohn@gmail.com',
    storeId: '19037502',
    content: '굿굿 아주 베리 굿굿',
  },
  {
    commentId: 17,
    email: 'alswl99710@gmail.com',
    storeId: '1130537615',
    content: '굿굿 아주 베리 굿굿굿',
  },
  {
    commentId: 18,
    email: 'rok.ksohn@gmail.com',
    storeId: '1130537615',
    content: '굿굿 아주 베리 굿굿굿굿',
  },
  {
    commentId: 19,
    email: 'sanbondeveloper@gmail.com',
    storeId: '1130537615',
    content: '굿굿 아주 베리 굿굿굿굿굿',
  },
  {
    commentId: 20,
    email: 'alswl99710@gmail.com',
    storeId: '21180713',
    content: '굿굿 아주 베리 굿굿굿굿굿굿',
  },
  {
    commentId: 21,
    email: 'bin000527@naver.com',
    storeId: '21180713',
    content: '굿굿 아주 베리 굿굿굿굿굿굿굿',
  },
  {
    commentId: 22,
    email: 'rok.ksohn@gmail.com',
    storeId: '21180713',
    content: '굿굿 아주 베리 굿굿굿굿굿굿굿굿',
  },
  {
    commentId: 23,
    email: 'bin000527@naver.com',
    storeId: '21180713',
    content: '굿굿 아주 베리 굿굿굿굿굿굿굿굿굿굿굿',
  },
  {
    commentId: 24,
    email: 'bin000527@naver.com',
    storeId: '26356307',
    content: '굿굿 아주 베리 굿굿굿굿굿굿굿굿굿굿굿굿',
  },
  {
    commentId: 25,
    email: 'bin000527@naver.com',
    storeId: '26356307',
    content: '규성이가 자신 있게 추천하는 맛집!',
  },
  {
    commentId: 26,
    email: 'bin000527@naver.com',
    storeId: '1453970380',
    content: '아주 마싯숴요',
  },
  {
    commentId: 27,
    email: 'sanbondeveloper@gmail.com',
    storeId: '1453970380',
    content: '집에 온 것 같은 맛이랍니다.',
  },
  {
    commentId: 28,
    email: 'alswl99710@gmail.com',
    storeId: '984709951',
    content: '맛있어용',
  },
  {
    commentId: 29,
    email: 'rok.ksohn@gmail.com',
    storeId: '984709951',
    content: '아주 마싯숴요',
  },
  {
    commentId: 30,
    email: 'bin000527@naver.com',
    storeId: '984709951',
    content: '예빈이가 자신 있게 추천하는 맛집 ! ',
  },
  {
    commentId: 31,
    email: 'rok.ksohn@gmail.com',
    storeId: '21366133',
    content: '규성이가 추천하는 맛집~ ㅎㅎ',
  },
  {
    commentId: 32,
    email: 'alswl99710@gmail.com',
    storeId: '21366133',
    content: '맛있어용',
  },
  {
    commentId: 33,
    email: 'bin000527@naver.com',
    storeId: '21366133',
    content: '갈 때마다 들리는 곳',
  },
  {
    commentId: 34,
    email: 'alswl99710@gmail.com',
    storeId: '1855041852',
    content: '엄마손맛집',
  },
  {
    commentId: 35,
    email: 'rok.ksohn@gmail.com',
    storeId: '1855041852',
    content: '인플루언서 제임스 씨가 자신 있게 추천하는 맛집 !!! ',
  },
  {
    commentId: 36,
    email: 'bin000527@naver.com',
    storeId: '1855041852',
    content: '맛집입니당',
  },
  {
    commentId: 37,
    email: 'rok.ksohn@gmail.com',
    storeId: '2092147534',
    content: '굿굿',
  },
  {
    commentId: 38,
    email: 'alswl99710@gmail.com',
    storeId: '2092147534',
    content: '맛있어용',
  },
  {
    commentId: 39,
    email: 'sanbondeveloper@gmail.com',
    storeId: '1386103378',
    content: '맛의 꼭대기',
  },
  {
    commentId: 40,
    email: 'alswl99710@gmail.com',
    storeId: '1386103378',
    content: '맛있어용',
  },
  {
    commentId: 41,
    email: 'rok.ksohn@gmail.com',
    storeId: '1386103378',
    content: '굿굿 또 가고 싶어요',
  },
  {
    commentId: 42,
    email: 'sanbondeveloper@gmail.com',
    storeId: '25634322',
    content: '맛의 꼭대기',
  },
  {
    commentId: 43,
    email: 'alswl99710@gmail.com',
    storeId: '25634322',
    content: '너무 좋아요',
  },
  {
    commentId: 44,
    email: 'rok.ksohn@gmail.com',
    storeId: '25634322',
    content: '또 가고 싶은 곳',
  },
  {
    commentId: 45,
    email: 'rok.ksohn@gmail.com',
    storeId: '1798961498',
    content: '어흥',
  },
  {
    commentId: 46,
    email: 'rok.ksohn@gmail.com',
    storeId: '1798961498',
    content: '중국집 맛의 꼭대기',
  },
  {
    commentId: 47,
    email: 'bin000527@naver.com',
    storeId: '1798961498',
    content: '수원 맛집 홍화루',
  },
  {
    commentId: 48,
    email: 'alswl99710@gmail.com',
    storeId: '1798961498',
    content: '귯귯',
  },
  {
    commentId: 49,
    email: 'rok.ksohn@gmail.com',
    storeId: '11162155',
    content: '귯귯',
  },
  {
    commentId: 50,
    email: 'sanbondeveloper@gmail.com',
    storeId: '11162155',
    content: '귯귯',
  },
  {
    commentId: 51,
    email: 'rok.ksohn@gmail.com',
    storeId: '11162155',
    content: '귯귯 아주 조와요',
  },
  {
    commentId: 52,
    email: 'bin000527@naver.com',
    storeId: '11162155',
    content: '귯귯귯',
  },
  {
    commentId: 53,
    email: 'bin000527@naver.com',
    storeId: '1349950333',
    content: '맛있어용',
  },
  {
    commentId: 54,
    email: 'sanbondeveloper@gmail.com',
    storeId: '1349950333',
    content: '경민이가 자신있게 추천하는 수원 맛집!',
  },
  {
    commentId: 55,
    email: 'bin000527@naver.com',
    storeId: '1349950333',
    content: '굿굿',
  },
  {
    commentId: 56,
    email: 'rok.ksohn@gmail.com',
    storeId: '14513092',
    content: '인플루언서 제임스 씨가 다녀간 요거트 맛집 ! ',
  },
  {
    commentId: 57,
    email: 'alswl99710@gmail.com',
    storeId: '14513092',
    content: '귯귯',
  },
  {
    commentId: 58,
    email: 'sanbondeveloper@gmail.com',
    storeId: '14513092',
    content: '산본 게 더 맛있어요',
  },
  {
    commentId: 59,
    email: 'bin000527@naver.com',
    storeId: '14513092',
    content: '좋아요',
  },
  {
    commentId: 60,
    email: 'sanbondeveloper@gmail.com',
    storeId: '14513092',
    content: '아주 좋아요',
  },
  {
    commentId: 61,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요1.',
  },
  {
    commentId: 62,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요2.',
  },
  {
    commentId: 63,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요3.',
  },
  {
    commentId: 64,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요4.',
  },
  {
    commentId: 65,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요5.',
  },
  {
    commentId: 66,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요6.',
  },
  {
    commentId: 67,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요7.',
  },
  {
    commentId: 68,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요8.',
  },
  {
    commentId: 69,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.9',
  },
  {
    commentId: 70,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요10.',
  },
  {
    commentId: 71,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.11',
  },
  {
    commentId: 72,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.12',
  },
  {
    commentId: 73,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.13',
  },
  {
    commentId: 74,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.14',
  },
  {
    commentId: 75,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.15',
  },
  {
    commentId: 76,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.16',
  },
  {
    commentId: 77,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.17',
  },
  {
    commentId: 78,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.18',
  },
  {
    commentId: 79,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.19',
  },
  {
    commentId: 80,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.20',
  },
  {
    commentId: 81,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.21',
  },
  {
    commentId: 82,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.22',
  },
  {
    commentId: 83,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.23',
  },
  {
    commentId: 84,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.24',
  },
  {
    commentId: 85,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 86,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 87,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 88,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 89,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 90,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 91,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 92,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 93,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 94,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 95,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 96,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 97,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 98,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 99,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 100,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 101,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 102,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 103,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 104,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 105,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 106,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 107,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 108,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 109,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 110,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 111,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 112,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 113,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 114,
    email: 'rok.ksohn@gmail.com',
    storeId: '8037122',
    content: '왠만하면 샐러드 안먹는데 여긴 정말 맛있어요!',
  },
  {
    commentId: 115,
    email: 'alswl99710@gmail.com',
    storeId: '8037122',
    content: '와따 마~ 사장님 좀 치네예~',
  },
  {
    commentId: 116,
    email: 'sanbondeveloper@gmail.com',
    storeId: '8037122',
    content: '솔직히 산본에 더 맛있는 데 많은데 여기도 나쁘지 않음 ㅇㅈ',
  },
  {
    commentId: 117,
    email: 'seojunpyo@zerobase.com',
    storeId: '8037122',
    content: '후식으로 나오는 커피가 나쁘지 않더군요',
  },
  {
    commentId: 118,
    email: 'bin000527@naver.com',
    storeId: '8037122',
    content: '끼야야야야호!!!! 너무 맛있어염!!! 뿜뿜!!!!',
  },
  {
    commentId: 119,
    email: 'kimdongkyu@zerobase.com',
    storeId: '8037122',
    content: '솔직히 마라탕만큼은 아닌데 진짜 맛있긴 합니다.',
  },
  {
    commentId: 120,
    email: 'chayunseul@zerobase.com',
    storeId: '8037122',
    content: '두 입 먹으니까 배불러요.. 냐하!',
  },
  {
    commentId: 121,
    email: 'kimkyungwoo@zerobase.com',
    storeId: '8037122',
    content: '음식 낫배드, 집 가고싶다',
  },
  {
    commentId: 122,
    email: 'ungmo2@zerobase.com',
    storeId: '8037122',
    content: 'JavaScript보단 맛 없네',
  },
  {
    commentId: 123,
    email: 'rok.ksohn@gmail.com',
    storeId: '26571895',
    content: '여기 단골인데 사장님 너무 좋아요.25',
  },
  {
    commentId: 124,
    email: 'sanbondeveloper@gmail.com',
    storeId: '27503321',
    content: '참기름 향과 김밥이 너무 잘 어울러져요',
  },
  {
    commentId: 125,
    email: 'kimkyungwoo@zerobase.com',
    storeId: '27503321',
    content: '맛있고 사장님이 친절하세요',
  },
  {
    commentId: 126,
    email: 'choisoomin@zerobase.com',
    storeId: '27503321',
    content: '당근 들어간 김밥 맛있어요💕',
  },
  {
    commentId: 127,
    email: 'parksunhwa@zerobase.com',
    storeId: '27503321',
    content: '오늘도 출근 도장 찍고 갑니다! 감사합니다 사장님!',
  },
  {
    commentId: 128,
    email: 'choiinae@zerobase.com',
    storeId: '27503321',
    content: '굿굿!! 분식 땡길 때마다 찾는 집입니다!!',
  },
  {
    commentId: 129,
    email: 'kwonhyukmin@zerobase.com',
    storeId: '27503321',
    content: '김밥 맛 아주 좋습니다 칭찬해요~',
  },
  {
    commentId: 130,
    email: 'ungmo2@zerobase.com',
    storeId: '27503321',
    content: '맛있습니다 칭찬 드리죠',
  },
  {
    commentId: 131,
    email: 'bin000527@naver.com',
    storeId: '27503321',
    content: '마이슐랭 보고 맛있어 보여서 찾아 갔는데, 꽤나 괜찮네요.',
  },
  {
    commentId: 132,
    email: 'bin000527@naver.com',
    storeId: '1273008691',
    content:
      '여기 가로수 점이 아니라 혹시 밀라노 점인가요? 본토 맛이 물씬 나네요',
  },
  {
    commentId: 133,
    email: 'ungmo2@zerobase.com',
    storeId: '1273008691',
    content: 'JavaScript 보단 맛 없지만 생각보다 나쁘지 않습니다. 칭찬합니다.',
  },
  {
    commentId: 134,
    email: 'rok.ksohn@gmail.com',
    storeId: '1273008691',
    content: '고향 생각 나네요....',
  },
  {
    commentId: 135,
    email: 'alswl99710@gmail.com',
    storeId: '1273008691',
    content: '사장님 피자 좀 치시네예~~~',
  },
  {
    commentId: 136,
    email: 'choiinae@zerobase.com',
    storeId: '1273008691',
    content: '하... 다이어트는 내일부터다...',
  },
  {
    commentId: 137,
    email: 'kimdongkyu@zerobase.com',
    storeId: '1273008691',
    content: '마라탕보단 아닌데 맛있습니다!',
  },
  {
    commentId: 138,
    email: 'leedongkyu@zerobase.com',
    storeId: '1273008691',
    content: '햄버거보다 맛있는게 있다니...',
  },
  {
    commentId: 139,
    email: 'seojunpyo@zerobase.com',
    storeId: '1273008691',
    content: '커피맛 피자는 없어요????',
  },
  {
    commentId: 140,
    email: 'parksunhwa@zerobase.com',
    storeId: '19037502',
    content:
      '진짜 장난치는게 아니라 여기서 먹는 버드와이저가 세상 제일 시원해요.',
  },
  {
    commentId: 141,
    email: 'chayunseul@zerobase.com',
    storeId: '19037502',
    content: '반 조각 먹었더니 배부르네요..냐하',
  },
  {
    commentId: 142,
    email: 'kwonhyukmin@zerobase.com',
    storeId: '19037502',
    content: '독일에서 먹던 피자보다 살짝 더 맛있어요',
  },
  {
    commentId: 143,
    email: 'kimkyungjae@zerobase.com',
    storeId: '19037502',
    content: '경재 + 피자 = 행복',
  },
  {
    commentId: 144,
    email: 'leedongkyu@zerobase.com',
    storeId: '19037502',
    content: '피자 6조각 쌉가능',
  },
  {
    commentId: 145,
    email: 'rok.ksohn@gmail.com',
    storeId: '1150223219',
    content: '맛있어요!! 굿굿',
  },
  {
    commentId: 146,
    email: 'alswl99710@gmail.com',
    storeId: '1150223219',
    content: '다음에 또 올게요~~',
  },
  {
    commentId: 147,
    email: 'choiinae@zerobase.com',
    storeId: '1150223219',
    content: '일 하시는 분들 모두 너무 친절해요ㅠㅠ',
  },
  {
    commentId: 148,
    email: 'kimdongkyu@zerobase.com',
    storeId: '1150223219',
    content: '꼭 와보고 싶었던 식당인데, 정말 만족스러웠습니다',
  },
  {
    commentId: 149,
    email: 'leedongkyu@zerobase.com',
    storeId: '1150223219',
    content: '음식 맛이 판타스틱 하답니다~',
  },
  {
    commentId: 150,
    email: 'seojunpyo@zerobase.com',
    storeId: '1150223219',
    content: '밥 먹고 후식으로 나오는 커피가 정말 맛있어요',
  },
  {
    commentId: 151,
    email: 'parksunhwa@zerobase.com',
    storeId: '1150223219',
    content: '내가 가장 아끼는 식당💕',
  },
  {
    commentId: 152,
    email: 'chayunseul@zerobase.com',
    storeId: '1150223219',
    content: '양이 정말 많아요!',
  },
  {
    commentId: 153,
    email: 'kwonhyukmin@zerobase.com',
    storeId: '1150223219',
    content:
      '독일에서 온 친구와 갔는데 친구가 정말 맛있다고 좋아했습니다!! ㅜㅜ',
  },
  {
    commentId: 154,
    email: 'kimkyungjae@zerobase.com',
    storeId: '19037502',
    content: '음식 맛은 물론이고 매장이 너무 청결하네요',
  },
  {
    commentId: 155,
    email: 'ungmo2@zerobase.com',
    storeId: '7880445',
    content: '일본 카레보단 아니지만 여기 카레도 나름 맛있어요.',
  },
  {
    commentId: 156,
    email: 'kimdongkyu@zerobase.com',
    storeId: '7880445',
    content: '아무도 마라탕 안 먹어줘서 왔는데 생각보다 나쁘지 않네요?',
  },
  {
    commentId: 157,
    email: 'leedongkyu@zerobase.com',
    storeId: '7880445',
    content: '햄버거 보다 맛있는게 있다니....',
  },
  {
    commentId: 158,
    email: 'seojunpyo@zerobase.com',
    storeId: '7880445',
    content:
      '라씨 처음 마셔봤는데, 아샷추 보단 낫지만 제가 만든 커피보단 별로네요. 카레는 맛있어요',
  },
  {
    commentId: 159,
    email: 'parksunhwa@zerobase.com',
    storeId: '7880445',
    content: '이거 먹으려고 강남 와요💕',
  },
  {
    commentId: 160,
    email: 'chayunseul@zerobase.com',
    storeId: '7880445',
    content: '카레 두 번 떠먹었더니 배불렀어요...냐하',
  },
  {
    commentId: 161,
    email: 'kwonhyukmin@zerobase.com',
    storeId: '7880445',
    content: 'Wow! Tastes amazing!',
  },
  {
    commentId: 162,
    email: 'kimkyungjae@zerobase.com',
    storeId: '19037502',
    content: '경재 + 카레 = 행복 경재',
  },
  {
    commentId: 163,
    email: 'rok.ksohn@gmail.com',
    storeId: '614667104',
    content:
      '샐러드는 도대체 누가 돈 주고 사먹나 궁금했는데 제가 여기서 사먹게 되네요👍',
  },
  {
    commentId: 164,
    email: 'alswl99710@gmail.com',
    storeId: '614667104',
    content: '이리 맛잇으면 제 지갑은 우짜라구예~',
  },
  {
    commentId: 165,
    email: 'kimdongkyu@zerobase.com',
    storeId: '614667104',
    content: '아무도 마라탕 안 먹어줘서 왔는데 생각보다 나쁘지 않네요?',
  },
  {
    commentId: 166,
    email: 'sanbondeveloper@gmail.com',
    storeId: '614667104',
    content: '몬스터플레이스 1호점이 아마 산본일걸요? 아님 말구',
  },
  {
    commentId: 167,
    email: 'bin000527@naver.com',
    storeId: '614667104',
    content: '왤케 맛있는데!!! 뿜뿜!!!!',
  },
  {
    commentId: 168,
    email: 'ungmo2@zerobase.com',
    storeId: '614667104',
    content: '자바스크립트 보단 맛 없네요. 하지만 괜찮아요.',
  },
  {
    commentId: 169,
    email: 'chayunseul@zerobase.com',
    storeId: '614667104',
    content: '양배추 2개 먹었더니 배불러요...냐하',
  },
  {
    commentId: 170,
    email: 'kimdongkyu@zerobase.com',
    storeId: '614667104',
    content: '我想吃麻辣烫.',
  },
  {
    commentId: 171,
    email: 'seojunpyo@zerobase.com',
    storeId: '614667104',
    content: '샐러드 드레싱 대신 커피 뿌려먹었더니 더 맛있어요!',
  },
];

const getCommentsByStoreId = (storeId) =>
  comments.filter((comment) => comment.storeId === storeId);

const createCommentId = () =>
  Math.max(...comments.map((comment) => comment.commentId), 0) + 1;

const createComment = (newComment) => {
  comments = [newComment, ...comments];

  return newComment;
};

const deleteComment = (commentId) => {
  const deletedComment = comments.find(
    (comment) => comment.commentId === +commentId,
  );

  comments = comments.filter((comment) => comment !== deletedComment);

  return deletedComment;
};

const getAllComments = () => comments;

module.exports = {
  getCommentsByStoreId,
  createComment,
  deleteComment,
  createCommentId,
  getAllComments,
};
